[workspace]
resolver = "3"
members = ["day-*"]

[workspace.package]
edition = "2024"
rust-version = "1.91.0"

[workspace.dependencies]
dhat = "0.3.3"
divan = "0.1.21"

[workspace.lints.clippy]
pedantic = "warn"

[profile.dhat]
inherits = "release"
debug = 1
